### ISSUE TITLE
broken url

### ISSUE THREAD

**Issue by br0kenbuild** [tingwei628/aspnetcore_webapp#8]
in your wiki https://github.com/tingwei628/aspnetcore_webapp/wiki/Docker
https://medium.com/the-code-review/clean-out-your-docker-images-containers-and-volumes-with-single-commands-b8e38253c271

**Comment by tingwei628** [comment]
Link is fixed now
https://hackernoon.com/clean-out-your-docker-images-containers-and-volumes-with-single-commands-b8e38253c271
